In [1]:
"""
combine fln.json with views in nodes.csv
    title:ID(Article), views
    A, 30293
    B, 20392
"""


import pandas as pd
import json

In [26]:
views_df = pd.read_csv("/Users/mark/Desktop/temp_data/20160613_views.csv", encoding='utf-8', 
                      usecols=['article', 'views'], index_col="article")

In [ ]:
import sqlite3
conn = sqlite3.connect('example.db')

views_df.to_sql("views.db", conn)

In [28]:
views_df.head(10)

                              views
article
0                              4329
!!!                             122
!!!EEEEE                          1
!!!Fuck_You!!!_and_Then_Some      9
!!!_(album)                      19
!Dame!_!Dame!_!Dame!              3
!HERO                             2
!Kung                            11
!Kung_language                   26
!Kung_people                     16

ERROR! Session/line number was not unique in database. History logging moved to new session 374

In [29]:
views_df.sample(10)

                                                    views
article
Special:WhatLinksHere/File:Maundy_Thursday_07_w...      1
Keith_Simpson_(American_football)                       1
Artarmon,_Sydney                                        1
Special:WhatLinksHere/Wikipedia:Selected_annive...      1
Talk:Coach_Barnum                                       1
Bretaigne_Windust                                       2
Heinlein_Prize_for_Advances_in_Space_Commercial...      5
User_talk%3ASuryanepal                                  1
Ckjjkc-nathani                                          1
Special:RecentChangesLinked/Talk:Ci%C3%A1ran_Wh...      1

In [30]:
# need to decode url string
import urllib

urllib.unquote("User_talk%3ASuryanepal").decode('utf8')

u'User_talk:Suryanepal'

In [34]:
# turn utf string into url string
urllib.quote("User_talk:Suryanepal", safe='')

'User_talk%3ASuryanepal'

In [19]:
fln_s_df = pd.read_csv("/Users/mark/Dropbox/Develop/Insight/knowledge_search/data/test_fln.csv", 
                       index_col=":START_ID(Article)", usecols=[":START_ID(Article)"])

In [20]:
fln_s_df.head()

Empty DataFrame
Columns: []
Index: [AccessibleComputing, Anarchism, AfghanistanHistory, AfghanistanGeography, AfghanistanPeople]

In [24]:
pd.concat([fln_s_df, views_df], axis=1, join_axes=[fln_s_df.index])

                                             Unnamed: 0 article  views
:START_ID(Article)
AccessibleComputing                                 NaN     NaN    NaN
Anarchism                                           NaN     NaN    NaN
AfghanistanHistory                                  NaN     NaN    NaN
AfghanistanGeography                                NaN     NaN    NaN
AfghanistanPeople                                   NaN     NaN    NaN
AfghanistanEconomy                                  NaN     NaN    NaN
AfghanistanCommunications                           NaN     NaN    NaN
AfghanistanTransportations                          NaN     NaN    NaN
AfghanistanMilitary                                 NaN     NaN    NaN
AfghanistanTransnationalIssues                      NaN     NaN    NaN
AssistiveTechnology                                 NaN     NaN    NaN
AmoeboidTaxa                                        NaN     NaN    NaN
Autism                                              NaN     NaN    NaN
AlbaniaHistory                                      NaN     NaN    NaN
AlbaniaGeography                                    NaN     NaN    NaN
AlbaniaPeople                                       NaN     NaN    NaN
AsWeMayThink                                        NaN     NaN    NaN
AllSaints                                           NaN     NaN    NaN
AlbaniaGovernment                                   NaN     NaN    NaN
AlbaniaEconomy                                      NaN     NaN    NaN
Albedo                                              NaN     NaN    NaN
AfroAsiaticLanguages                                NaN     NaN    NaN
ArtificalLanguages                                  NaN     NaN    NaN
AbacuS                                              NaN     NaN    NaN
AbalonE                                             NaN     NaN    NaN
AbbadideS                                           NaN     NaN    NaN
AbbesS                                              NaN     NaN    NaN
AbbevilleFrance                                     NaN     NaN    NaN
AbbeY                                               NaN     NaN    NaN
AbboT                                               NaN     NaN    NaN
...                                                 ...     ...    ...
Crooms AOIT                                         NaN     NaN    NaN
Collective Tuning Initiative                        NaN     NaN    NaN
Scheungraber                                        NaN     NaN    NaN
Wake Wood                                           NaN     NaN    NaN
Template:Germany-mil-unit-stub                      NaN     NaN    NaN
Wikipedia:Articles for deletion/Mr. Tararam         NaN     NaN    NaN
Template:US-mil-unit-stub                           NaN     NaN    NaN
Template:France-mil-unit-stub                       NaN     NaN    NaN
Hans Booys                                          NaN     NaN    NaN
File:Fernando Paz Castillo.jpg                      NaN     NaN    NaN
Asvs                                                NaN     NaN    NaN
Anaikudam                                           NaN     NaN    NaN
Marcus Townsend                                     NaN     NaN    NaN
Grime daily                                         NaN     NaN    NaN
Charity Lords of the Ring                           NaN     NaN    NaN
Ivan Lozenkov                                       NaN     NaN    NaN
Geoffrey McGonagle                                  NaN     NaN    NaN
Johnny Fallon                                       NaN     NaN    NaN
Ilija grahovac                                      NaN     NaN    NaN
File:Jet Blue Terminal5 logo.jpg                    NaN     NaN    NaN
Groudle Glen Bogie Coaches                          NaN     NaN    NaN
Andimadam                                           NaN     NaN    NaN
Fred Ford (football manager)                        NaN     NaN    NaN
Panmure House                                       NaN     NaN    NaN
钟骏源                                                 NaN     NaN    NaN
Domestic sewage                                     NaN     NaN    NaN
Fifa milan                                          NaN     NaN    NaN
River maintenance flow                              NaN     NaN    NaN
Muljangori-Oreum                                    NaN     NaN    NaN
Agricultural water                                  NaN     NaN    NaN

[373 rows x 3 columns]

In [56]:
views_df.iloc[99800:998080]

                                       views
article
Agricultural_University_of_Iceland         6
Agricultural_University_of_Norway          1
Agricultural_University_of_Tajikistan      4
Agricultural_University_of_Tirana          7
Agricultural_Wheel                         5
Agricultural_aircraft                     29
Agricultural_and_Biological_Chemistry      1
Agricultural_and_Forest_Meteorology        5
Agricultural_attach%C3%A9                 11
Agricultural_belt                          1
Agricultural_biodiversity                 23
Agricultural_biotechnology                29
Agricultural_buildings                     1
Agricultural_chemistry                    55
Agricultural_collectivisation              1
Agricultural_college                       2
Agricultural_commune                       4
Agricultural_cooperative                  99
Agricultural_cycle                        22
Agricultural_diversification              28
Agricultural_economics                    99
Agricultural_education                    56
Agricultural_engine                        1
Agricultural_engineering                 118
Agricultural_equipment                     9
Agricultural_experiment_station           14
Agricultural_extension                    81
Agricultural_fencing                      33
Agricultural_geography                     5
Agricultural_history_of_Peru              13
...                                      ...
Heathenreel                                3
Heathenry_(new_religious_movement)       121
Heather                                  122
Heather%20Menzies                          1
Heather,_Lady_McCartney                    1
Heather_(fabric)                          36
Heather_(given_name)                      19
Heather_(surname)                          5
Heather_Anderson                           1
Heather_Angel_(actress)                   34
Heather_Anne_Campbell                     73
Heather_Armbrust                           7
Heather_Ashley_Chase                      24
Heather_Ashton                             5
Heather_B._Gardner                        31
Heather_Bambrick                           7
Heather_Bishoff                            2
Heather_Black                              5
Heather_Bown                               7
Heather_Bresch                            29
Heather_Brooke                            76
Heather_Burge                             36
Heather_Burns                             80
Heather_Casler                             1
Heather_Chasen                            13
Heather_Christensen                       20
Heather_Couper                             6
Heather_Craney                             1
Heather_Cream                              4
Heather_Crowe                              3

[898280 rows x 1 columns]

In [78]:
views_df.loc["Agricultural_Wheel"]

views    5
Name: Agricultural_Wheel, dtype: float64

In [83]:
views_df.loc["Accessible_computing"]

views    1
Name: Accessible_computing, dtype: float64

In [79]:
fln_s_df.index[:10]

Index([u'AccessibleComputing', u'Anarchism', u'AfghanistanHistory',
       u'AfghanistanGeography', u'AfghanistanPeople', u'AfghanistanEconomy',
       u'AfghanistanCommunications', u'AfghanistanTransportations',
       u'AfghanistanMilitary', u'AfghanistanTransnationalIssues'],
      dtype='object', name=u':START_ID(Article)')

# Diff Lib Fuzzy Matching

In [57]:
import difflib

In [59]:
s = "Grime daily"

In [77]:
views_df.index[:100].map(decode_url_string)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-5: ordinal not in range(128)

In [76]:
def decode_url_string(in_string):
    return urllib.unquote(in_string).decode('utf-8').replace("_", " ")

In [74]:
s.title()

'Grime Daily'

In [75]:
df2.index.map(lambda x: difflib.get_close_matches(x, df1.index)[0])

NameError: name 'df2' is not defined